## lhie1
## github地址   https://github.com/lhie1/Rules.git

## 作者名         lhie1
## 作者库名       Rules
## 作者分支名     master
## 同步分支名     lhie1

name: lhie1-sync
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-lhie1-Rules
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync lhie1-Rules
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lhie1/Rules.git"
          source_branch: "master"
          destination_branch: "lhie1"
          github_token: ${{ secrets.PAT }}
