# This is a basic workflow to help you get started with Actions
## ziye 
## github地址 https://github.com/6Svip120apk69
## TG频道地址  https://t.me/ziyescript
## TG交流群   https://t.me/joinchat/AAAAAE7XHm-q1-7Np-tF3g
## boxjs链接  https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/ziye.boxjs.json
## 新建一个库，此文件路径为 .github/workflows/ziye-sync.yml 
## 打开教程链接 https://www.jianshu.com/p/bb82b3ad1d11 ，申请PAT（勾选时尽量全部勾选 ），
## 找到Settings--secrets--New repository secret---name填写PAT   value填写PAT的值        

name: ziye-sync

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  ##push:
    ##branches: [ main ]
  ##pull_request:
    ##branches: [ main ]
  schedule:
    - cron: '1 */3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-6Svip120apk69-gitee_q8qsTAUA_cThxc1RBVUE
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   #build:
   repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      # Runs a single command using the runners shell
      ##- name: Run a one-line script
      ##  run: echo Hello, world!
      - name: sync 6Svip120apk69-gitee_q8qsTAUA_cThxc1RBVUE
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE.git"
          source_branch: "main"
          destination_branch: "ZIYE"
          github_token: ${{ secrets.PAT }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
